version: "3.9"

services:
  movie_scraper:
    build: .
    volumes:
      - .:/app:rw  # Mount the current directory as the working directory inside the container
    ports:
    - 3030:3030
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}  # Access API key from environment variable
    networks:
      - my-network
    links:
      - movies_db

networks:
  my-network:
    external: true
