version: "3.9"

services:
  movies_db:
    image: movies_db
    build:
      context: .
      dockerfile: ./database/dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  movie_scraper:
    image: movie_scraper
    build: .
    volumes:
      - .:/app:rw  # Mount the current directory as the working directory inside the container
    ports:
      - "8050:8050"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}  # Access API key from environment variable
    networks:
      - my-network
    depends_on:
      - movies_db

networks:
  my-network:
    driver: bridge
