version: "3.8"

services:
  movie_scraper:
    build: .
    volumes:
      - .:/app:rw  # Mount the current directory as the working directory inside the container
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}  # Access API key from environment variable
