version: "3.9"

services:
  movies_db:
    image: movies_db:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  pgdata: {}

networks:
  my-network:
    driver: bridge