FROM postgres:latest

ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

RUN mkdir -p /docker-entrypoint-initdb.d/

COPY create_tables.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

CMD ["postgres", "-p", "5432"]
